stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Building function..."
              # Your build commands here (e.g., npm install, build, package)
            displayName: "Build Function"

  - stage: Deploy
    dependsOn:
      - Build
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            displayName: "Download Service Account Key"
            inputs:
              secureFile: compute-iam-test-c777ed5d2926.json
          - script: |
              echo "Deploying function..."
              gcloud auth activate-service-account --key-file=$(secureFile.secureFilePath)
              gcloud functions deploy [FUNCTION_NAME] --runtime [RUNTIME] --trigger-http --region [REGION] --project [PROJECT_ID]
            displayName: "Deploy Function"
